### ISSUE TITLE
Update doc with TN2 params

### ISSUE THREAD

**Issue by avive** [karma-coin/karmacoin-docs#3]
Update this doc with TN2 params:
https://github.com/karma-coin/karmacoin-docs/blob/main/versioned_docs/version-0.1.0/testnet/tn2_parameters.md

**Comment by avive** [comment]
- https://guide.kusama.network/docs/kusama-parameters/
- https://guide.kusama.network/docs/maintain-polkadot-parameters

**Comment by HolyGrease** [comment]
https://github.com/karma-coin/karmacoin-docs/pull/5

**Comment by avive** [comment]
We also need to update this doc for TN2 and list all txs supported from the js ui:
https://karmaco.in/docs/testnet/basics

We also need to update the validators docs here:
https://karmaco.in/docs/testnet/validator

For future PRs for docs:
1. Please clone this repo https://github.com/avive/karmacoin-docs - the org repo is just tracking this one.
2. Please update all external links in MDs to absolute ones.

**Comment by avive** [comment]
I think that we also need to discuss changing the base account units from Kcents to KCoin. So KCoin has 6 decimal units so 1 KCoin is 6 million KCents. Similar to DOT in polkadot. Correct?

**Comment by HolyGrease** [comment]
Decimals are describe [here](https://karmaco.in/docs/testnet/tn2-parameters#precision)

**Comment by avive** [comment]
I'm asking what should be the coin name label in explorer - shouldn't it be KCoin and NOT KCents?

**Comment by avive** [comment]
Please remember to update this https://karmaco.in/docs/testnet/basics via a PR for testnet 2 - with all the txs we support!

**Comment by HolyGrease** [comment]
@avive https://github.com/avive/karmacoin-docs/pull/2
